require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp" -- searches for a init.lua file in that directory 
require "user.nvim-tree"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.gitsigns"
require "user.comment"
require "user.bufferline"
require "user.toggleterm"
require "user.alpha"
require "user.sessions"
require "user.lualine"
